// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Copyright (c) Microsoft Corporation
//
// Author: Jon Lange <jlange@microsoft.com>

use crate::page_tables::page_align_up;

use bootdefs::boot_params::BootParamBlock;

/// Page table self-map level 3 index
pub const PGTABLE_LVL3_IDX_PTE_SELFMAP: usize = 493;

/// This is a structure generated by the boot image loader that contains the
/// execution context information required to launch the loaded boot image.
#[derive(Debug)]
pub struct BootImageContext {
    pub entry_point: u64,
    pub launch_info_vaddr: u64,
    pub initial_stack: u64,
    pub initial_stack_base: u64,
    pub paging_root: u64,
}

/// This structure is also generated by the boot image loader to describe
/// information about the boot image to that is needed to complete the
/// preparation of the boot image by the boot image host.
#[derive(Debug)]
pub struct BootImageInfo {
    pub context: BootImageContext,
    pub kernel_pdpt_paddr: u64,
    pub kernel_pml4e_index: usize,
    pub boot_params_paddr: u64,
    pub cpuid_paddr: u64,
    pub secrets_paddr: u64,
}

/// This is a structure of kernel launch information that is generated by the
/// boot image host, which will be inserted into the kernel launch parameters
/// and mixed with launch parameters generated by the boot image builder.
#[derive(Debug)]
pub struct BootImageParams<'a> {
    pub stage2_start: u64,
    pub kernel_fs_start: u64,
    pub kernel_fs_end: u64,
    pub vtom: u64,
    pub debug_serial_port: u16,
    pub boot_params: &'a BootParamBlock,
}

pub trait BootImageHost<'a> {
    /// Displays an error message.
    fn display_error(&self, string: &str);

    /// Obtains an ELF file containing the kernel image.
    fn get_kernel_image(&self) -> Result<&'a [u8], ()>;

    /// Obtains the physical address bounds of the kernel region.  This returns
    /// a tuple of (base physical address, page count).
    fn get_kernel_phys_region(&self) -> (u64, u64);

    /// Obtains the confidential address bitmask used in the current
    /// environment.  This may be zero if the page tables will be updated once
    /// the boot image is loaded.
    fn get_confidential_address_mask(&self) -> u64;

    /// Inserts data into the boot image, or empty pages if no data is
    /// supplied..
    fn add_page_data(
        &mut self,
        paddr: u64,
        contents: Option<&[u8]>,
        total_size: u64,
    ) -> Result<(), ()>;
}

pub fn add_page_data<'a, H: BootImageHost<'a>>(
    host: &mut H,
    paddr: u64,
    contents: Option<&[u8]>,
    total_size: u64,
) -> Result<(), ()> {
    host.add_page_data(paddr, contents, total_size)
        .inspect_err(|_| {
            host.display_error("Failed to add page contents to image");
        })
}

pub fn add_page_contents<'a, H: BootImageHost<'a>>(
    host: &mut H,
    paddr: u64,
    contents: &[u8],
) -> Result<(), ()> {
    add_page_data(
        host,
        paddr,
        Some(contents),
        page_align_up(contents.len() as u64),
    )
}
